### ISSUE TITLE
Anonymous controller RSpec test fails after adding hotwire-rails gem to the codebase

### ISSUE THREAD

**Issue by siwS** [hotwired/hotwire-rails#42]
We have [an anonymous controller RSpec test](https://relishapp.com/rspec/rspec-rails/v/2-14/docs/controller-specs/anonymous-controller) for our global error handler, which started failing when we add the `hotwire-rails` gem to the codebase. Removing the gem fixes the spec. The error only happens in tests - everything works in the development environment. Any help would be appreciated.

Versions: 
* "rails", "~> 6.1.4"
* "hotwire-rails", "~> 0.1.3"
* "rspec", ~> "3.10.0"

Error stacktrace:

```
    NoMethodError:
       Could not render layout: undefined method `empty?' for nil:NilClass
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/lookup_context.rb:219:in `normalize_name'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/lookup_context.rb:168:in `args_for_lookup'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/lookup_context.rb:132:in `find_all'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/layouts.rb:328:in `_layout'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/layouts.rb:414:in `_default_layout'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/layouts.rb:390:in `block in _layout_for_option'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/renderer/template_renderer.rb:104:in `resolve_layout'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/renderer/template_renderer.rb:84:in `find_layout'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/renderer/template_renderer.rb:67:in `render_with_layout'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/renderer/template_renderer.rb:11:in `render'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/rendering.rb:117:in `block in _render_template'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/base.rb:273:in `in_rendering_context'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/rendering.rb:116:in `_render_template'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/streaming.rb:218:in `_render_template'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionview-6.1.4.1/lib/action_view/rendering.rb:103:in `render_to_body'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.1/lib/abstract_controller/rendering.rb:25:in `render'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/rendering.rb:36:in `render'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:46:in `block (2 levels) in render'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:46:in `block in render'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:86:in `cleanup_view_runtime'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
     # /Users/sofia/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.1/lib/action_controller/metal/instrumentation.rb:45:in `render'
``` 

Digging into it, we narrowed it down to the actionview `LookupContext#normalize_name` method in this line:
https://github.com/rails/rails/blob/6-1-stable/actionview/lib/action_view/lookup_context.rb#L219

The `name` parameter is empty (""), and therefore parts.first is nil.

```ruby
   parts    = name.to_s.split("/")
   parts.shift if parts.first.empty?
```

The code and spec that is failing, to help reproduce:

```ruby
# Error module to Handle errors globally
# include Error::ErrorHandler in application_controller.rb
module Error
  module ErrorHandler

    # public/page that we render for each error
    ERROR_STATUSES = {
      "StandardError" => 500,
      "ArgumentError" => 422,
      "ActiveRecord::RecordNotFound" => 404,
    }

    def self.included(clazz)
      clazz.class_eval do
        ERROR_STATUSES.keys.each do |error|
          rescue_from error.constantize do |e|
            respond(error, e)
          end
        end
      end
    end

    private

    def respond(error, e)
      Rails.logger.error("Error::ErrorHandler: #{error}, #{e}")
      status = ERROR_STATUSES[error]
      # 
      #
      # This is the line that raises the error in test:
      #
      render file: "#{Rails.root}/public/#{status}.html", status: status
    end
  end
end
```

```ruby
RSpec.describe "Error::ErrorHandler", type: :controller do

  controller(ActionController::Base) do
    include Error::ErrorHandler
    attr_accessor :error

    def fake_action
      raise error
    end
  end

  before do
    routes.draw {
      get "fake_action" => "anonymous#fake_action"
    }
  end

  ERRORS = [ArgumentError,
            StandardError,
            ActiveRecord::RecordNotFound]

  # Messages from template file that is rendered
  ERROR_MESSAGES = {
    "ActiveRecord::RecordNotFound" => "The page you were looking for doesn't exist (404)",
    "ArgumentError" => "The change you wanted was rejected (422)",
    "StandardError" => "We're sorry, but something went wrong (500)",
  }

  ERRORS.each do |error|
    context "#{error}" do
      # These tests are failing when adding Hotwire
      it "rescues the error and renders error page" do
        controller.error = error
        get :fake_action, :format => "html"

        expect(response.body).to include(ERROR_MESSAGES[error.to_s])
        expect(response.status).to eq(Error::ErrorHandler::ERROR_STATUSES[error.to_s])
      end
    end
  end
end
```

**Comment by dhh** [comment]
Thanks for the report. Hotwire-rails is itself just a thin wrapper to install stimulus-rails and turbo-rails. I could imagine that maybe the controllers in turbo-rails are triggering something? Or maybe some of your other dependencies got updated. Either way, will need a deeper isolation of the problem before I can assist.
